### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mracos** [tmbb/makeup_erlang#12]
Couple improvements that I think would be nice to do (referencend from [this comment](https://github.com/tmbb/makeup_erlang/issues/4#issuecomment-541239289)).

#### Improvements
- [x] Highlight the module in a function call `module:function()` ([example](https://github.com/apache/couchdb/blob/dc054e7ddcc3ea059e1f86a7039cf86912ab1052/src/couch/src/couch_db_updater.erl#L96))
- [x] Improve the module attribute combinator to handle specs `-spec function(type()) -> type().` ([example](https://github.com/ninenines/cowboy/blob/63b17e4edf666d995ec86cdcda17a62ba5ebc423/src/cowboy_req.erl#L172))
- [x] Add a combinator for record like syntax `#record{attribute = value}` ([example](https://github.com/apache/couchdb/blob/dc054e7ddcc3ea059e1f86a7039cf86912ab1052/src/couch/src/couch_db_updater.erl#L73))

#### Maybe improvements?
(Things I would like to discuss)

- [x] Have a combinator for function names `function/0`?
- [x] ~~Highlight attributes (`binary`, `bitstring`, number of bytes) in binary pattern match `<<"string", Rest/binary>>`?~~ (I'm pretty ok with the way it is)

**Comment by tmbb** [comment]
>  Have a combinator for function names function/0?

I haven't used Erlang enough to decide whether that is a good idea, so I default to your judgement.

The rest seems ok

**Comment by mracos** [comment]
>> Have a combinator for function names function/0?

> I haven't used Erlang enough to decide whether that is a good idea, so I default to your judgement.

@josevalim what are your thoughts about this specific topic?

**Comment by josevalim** [comment]
> Have a combinator for function names function/0?

I checked my editor and it is a :+1: from me. It would also apply on things like `fun function/0`, which is welcome.
