### ISSUE TITLE
Warning when compiling

### ISSUE THREAD

**Issue by slondr** [tmbb/makeup_erlang#23]
I get the following when compiling:
```
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
Warning:   lib/makeup/lexers/erlang_lexer.ex:250: Makeup.Lexers.ErlangLexer
```

**Comment by bradhanks** [comment]
I submitted a PR to fix this: https://github.com/elixir-makeup/makeup/pull/63

**Comment by josevalim** [comment]
Closing in favor of the PR!

**Comment by josevalim** [comment]
Fixed in https://github.com/elixir-makeup/makeup_erlang/commit/a5529648769043d95daff0a515b82f29e24d8014
