### ISSUE TITLE
Create a release of this package in Hex

### ISSUE THREAD

**Issue by mracos** [tmbb/makeup_erlang#4]
When we get to a point where we can use this package to highlight `erlang` code in `ex_doc`, we should create a release of this package in Hex as to not include the dependency straight from github.

**Comment by mracos** [comment]
I have gathered a couple of big files from erlang projects like `ejarbbed` and `couchdb` as to test the highlighter and I'm pretty sure that we are good to go (it's looking good :smile:).

You can see the highlighter in action [here](https://inspiring-easley-03dc40.netlify.com/languages.html) (the offline version in case the website goes out is [here](https://github.com/tmbb/makeup_erlang/files/3719713/hexdocs.zip))

I think we have achieved a kind of MVP for this library so it can be released in Hex.

I have mapped some improvements but we can do them incrementally, so I will open another issue for it.

WDYT @tmbb? cc @josevalim

**Comment by josevalim** [comment]
I think we can go ahead and do it. @mracos do you want to have the honors? First you will need to update both the docs and package information in the `mix.exs`. Luckily you can copy `makeup_elixir` for it. Then you can push it to hex and add @tmbb as an owner.

**Comment by mracos** [comment]
Published to Hex!
https://hex.pm/packages/makeup_erlang

**Comment by josevalim** [comment]
Congratulations!
